// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdLDMtfho-asPfNcqd_YLjmU9OFRQxTU',
    appId: '1:11262065114:web:39f04aa77fcae23bcc68e3',
    messagingSenderId: '11262065114',
    projectId: 'flutterkitaphana',
    authDomain: 'flutterkitaphana.firebaseapp.com',
    storageBucket: 'flutterkitaphana.firebasestorage.app',
    measurementId: 'G-XGH5V1M76S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcxufG3GR10E97J6OLmopiDPMgCpHHwCo',
    appId: '1:11262065114:android:d887e224af152b39cc68e3',
    messagingSenderId: '11262065114',
    projectId: 'flutterkitaphana',
    storageBucket: 'flutterkitaphana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1nWbnUaUkeydme-ROExHTxNVqOJG6Mw',
    appId: '1:11262065114:ios:8f6fef2ff675b011cc68e3',
    messagingSenderId: '11262065114',
    projectId: 'flutterkitaphana',
    storageBucket: 'flutterkitaphana.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1nWbnUaUkeydme-ROExHTxNVqOJG6Mw',
    appId: '1:11262065114:ios:8f6fef2ff675b011cc68e3',
    messagingSenderId: '11262065114',
    projectId: 'flutterkitaphana',
    storageBucket: 'flutterkitaphana.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdLDMtfho-asPfNcqd_YLjmU9OFRQxTU',
    appId: '1:11262065114:web:0219283ae0e9c1d6cc68e3',
    messagingSenderId: '11262065114',
    projectId: 'flutterkitaphana',
    authDomain: 'flutterkitaphana.firebaseapp.com',
    storageBucket: 'flutterkitaphana.firebasestorage.app',
    measurementId: 'G-59G1NPJZCM',
  );
}
